codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  round: down
  status:
    patch: # minimum coverage needed based only on the new code introduced on the PR
      default: off
      pr_coverage:
        target: 90%
    project:
      default: off
      minimum: # minimum target of coverage needed to pass the check
        target: 90%
    patch: off
    changes: no
