codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  round: down

  status:
    project:
      tests:  # declare a new status context "tests"
        target: 100%  # we always want 100% coverage here
        paths: "spec/"  # only include coverage in "tests/" folder
      app:  # declare a new status context "app"
        paths: "!spec/"  # remove all files in "tests/"
    patch:
      default:
        # basic
        target: auto
        threshold: null
        base: auto 
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
