codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  round: down

  status:
    project: 
      default:
        target: 90%
            
    patch: 
      default:
        target: 90%
        base: pr
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
