codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  round: down

  status:
    project:
      default: off
      minimum: # minimum target of coverage needed to pass the check
        target: 90%
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
  require_base: no        # [yes :: must have a base report to post]
  require_head: no       # [yes :: must have a head report to post]
