codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  round: down

  status:
    patch: # minimum coverage needed based only on the new code introduced on the PR
      default: off
      pr_coverage:
        target: 60%
    project:
      default:
        # basic
        target: auto
        threshold: null
        base: auto 
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
